# This is a basic workflow to help you get started with Actions

name: Generate weekly habits

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * MON'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    env: 
      NOTION_HABIT_DATABASE_ID: ${{ secrets.NOTION_HABIT_DATABASE_ID }}
      NOTION_TASK_DATABASE_ID: ${{ secrets.NOTION_TASK_DATABASE_ID }}
      NOTION_SECRET: ${{ secrets.NOTION_SECRET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install

      # Runs a single command using the runners shell
      - name: Generate weekly habits on Notion
        run: yarn run generate-habits
