# This is a basic workflow to help you get started with Actions

name: Update done date for lyf tasks

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */4 * * *' #every 4 hours
    - cron: '15 21 * * *' #every day at 21h15 (before review)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    env:
      NOTION_HABIT_DATABASE_ID: ${{ secrets.NOTION_HABIT_DATABASE_ID }}
      NOTION_TASK_DATABASE_ID: ${{ secrets.NOTION_TASK_DATABASE_ID }}
      NOTION_SECRET: ${{ secrets.NOTION_SECRET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      
      - name: Download last list of completed tasks
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tasks.yml
          name: completed-tasks-list
    
      - name: Update done date for tasks completed today
        run: yarn run update-completed-tasks-done-date

      - name: Retain completed-tasks.json
        uses: actions/upload-artifact@v2
        with:
          name: completed-tasks-list
          path: ./completed-tasks.json
          retention-days: 1
